In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\igbekele olatimehin\anaconda3\lib\site-packages (1.5.3)
Requirement already satisfied: numpy>=1.21.0 in c:\users\igbekele olatimehin\anaconda3\lib\site-packages (from pandas) (1.23.5)
Requirement already satisfied: pytz>=2020.1 in c:\users\igbekele olatimehin\anaconda3\lib\site-packages (from pandas) (2022.7)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\igbekele olatimehin\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\igbekele olatimehin\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("Churn_Modelling.csv")

In [4]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,NaN,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39.0,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35.0,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36.0,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1,0,38190.78,0

In [5]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,NaN,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0

In [6]:
df.tail()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,9996,15606229,Obijiaku,771,France,Male,39.0,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35.0,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36.0,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1,0,38190.78,0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              9999 non-null   float64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(3), int64(8), object(3)
memory usage: 1.1+ MB

In [8]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,9999.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921492,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.488286,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [9]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,NaN,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39.0,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35.0,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36.0,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1,0,38190.78,0

In [10]:
df["Balance"] # single column

0            0.00
1        83807.86
2       159660.80
3            0.00
4       125510.82
          ...
9995         0.00
9996     57369.61
9997         0.00
9998     75075.31
9999    130142.79
Name: Balance, Length: 10000, dtype: float64

In [11]:
df["Latest_Balance"] = df["Balance"] + 500 # create new column

In [12]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Latest_Balance
0,1,15634602,Hargrave,619,France,Female,NaN,2,0.00,1,1,1,101348.88,1,500.00
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0,84307.86
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1,160160.80
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0,500.00
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0,126010.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39.0,5,0.00,2,1,0,96270.64,0,500.00
9996,9997,15569892,Johnstone,516,France,Male,35.0,10,57369.61,1,1,1,101699.77,0,57869.61
9997,9998,15584532,Liu,709,France,Female,36.0,7,0.00,1,0,1,42085.58,1,500.00
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1,0,92888.52,1,75575.31
9999,10000,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1,0,38190.78,0,130642.79

In [14]:
df.columns # check the entire column

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited', 'Latest_Balance'],
      dtype='object')

In [15]:
df.sort_values("Age") # sort column age ascending

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Latest_Balance
3512,3513,15657779,Boylan,806,Spain,Male,18.0,3,0.00,2,1,1,86994.54,0,500.00
2021,2022,15795519,Vasiliev,716,Germany,Female,18.0,3,128743.80,1,0,0,197322.13,0,129243.80
9029,9030,15722701,Bruno,594,Germany,Male,18.0,1,132694.73,1,1,0,167689.56,0,133194.73
3517,3518,15757821,Burgess,771,Spain,Male,18.0,1,0.00,2,0,0,41542.95,0,500.00
4716,4717,15805764,Hallahan,646,France,Male,18.0,10,0.00,2,0,1,52795.15,0,500.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3033,3034,15578006,Yao,787,France,Female,85.0,10,0.00,2,1,1,116537.96,0,500.00
2458,2459,15813303,Rearick,513,Spain,Male,88.0,10,0.00,2,1,1,52952.24,0,500.00
6759,6760,15660878,T'ien,705,France,Male,92.0,1,126076.24,2,1,1,34436.83,0,126576.24
6443,6444,15764927,Rogova,753,France,Male,92.0,3,121513.31,1,0,1,195563.99,0,122013.31
0,1,15634602,Hargrave,619,France,Female,NaN,2,0.00,1,1,1,101348.88,1,500.00

In [16]:
# create anotheer column 
df["Random Column"] = "Good day"
df.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Latest_Balance,Random Column
0,1,15634602,Hargrave,619,France,Female,NaN,2,0.00,1,1,1,101348.88,1,500.00,Good day
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0,84307.86,Good day
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1,160160.80,Good day
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0,500.00,Good day
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0,126010.82,Good day

In [18]:
# access row
df[10:12]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Latest_Balance,Random Column
10,11,15767821,Bearce,528,France,Male,31.0,6,102016.72,2,0,0,80181.12,0,102516.72,Good day
11,12,15737173,Andrews,497,Spain,Male,24.0,3,0.00,2,1,0,76390.01,0,500.00,Good day

In [19]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Latest_Balance,Random Column
0,1,15634602,Hargrave,619,France,Female,NaN,2,0.00,1,1,1,101348.88,1,500.00,Good day
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0,84307.86,Good day
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1,160160.80,Good day
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0,500.00,Good day
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0,126010.82,Good day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39.0,5,0.00,2,1,0,96270.64,0,500.00,Good day
9996,9997,15569892,Johnstone,516,France,Male,35.0,10,57369.61,1,1,1,101699.77,0,57869.61,Good day
9997,9998,15584532,Liu,709,France,Female,36.0,7,0.00,1,0,1,42085.58,1,500.00,Good day
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1,0,92888.52,1,75575.31,Good day
9999,10000,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1,0,38190.78,0,130642.79,Good day

In [20]:
# creating new df but only if age is greater than 50
new_df_Age_greater_50 = df[df.Age > 50]

In [21]:
new_df_Age_greater_50

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Latest_Balance,Random Column
16,17,15737452,Romeo,653,Germany,Male,58.0,1,132602.88,1,1,0,5097.67,1,133102.88,Good day
41,42,15738148,Clarke,465,France,Female,51.0,8,122522.32,1,0,0,181297.65,1,123022.32,Good day
42,43,15687946,Osborne,556,France,Female,61.0,2,117419.35,1,1,1,94153.83,0,117919.35,Good day
44,45,15684171,Bianchi,660,Spain,Female,61.0,5,155931.11,1,1,1,158338.39,0,156431.11,Good day
58,59,15623944,T'ien,511,Spain,Female,66.0,4,0.00,1,1,0,1643.11,1,500.00,Good day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9936,9937,15653037,Parks,609,France,Male,77.0,1,0.00,1,0,1,18708.76,0,500.00,Good day
9939,9940,15808971,Lajoie,693,Spain,Female,57.0,9,0.00,2,1,1,135502.77,0,500.00,Good day
9948,9949,15735078,Onwughara,724,Germany,Female,53.0,1,139687.66,2,1,1,12913.92,0,140187.66,Good day
9979,9980,15692664,Diribe,677,France,Female,58.0,1,90022.85,1,0,1,2988.28,0,90522.85,Good day
9991,9992,15769959,Ajuluchukwu,597,France,Female,53.0,4,88381.21,1,1,0,69384.71,1,88881.21,Good day

In [22]:
new_df_Age_greater_50.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Latest_Balance,Random Column
16,17,15737452,Romeo,653,Germany,Male,58.0,1,132602.88,1,1,0,5097.67,1,133102.88,Good day
41,42,15738148,Clarke,465,France,Female,51.0,8,122522.32,1,0,0,181297.65,1,123022.32,Good day
42,43,15687946,Osborne,556,France,Female,61.0,2,117419.35,1,1,1,94153.83,0,117919.35,Good day
44,45,15684171,Bianchi,660,Spain,Female,61.0,5,155931.11,1,1,1,158338.39,0,156431.11,Good day
58,59,15623944,T'ien,511,Spain,Female,66.0,4,0.00,1,1,0,1643.11,1,500.00,Good day

In [23]:
df.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Latest_Balance,Random Column
0,1,15634602,Hargrave,619,France,Female,NaN,2,0.00,1,1,1,101348.88,1,500.00,Good day
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0,84307.86,Good day
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1,160160.80,Good day
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0,500.00,Good day
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0,126010.82,Good day

In [25]:
mean_age = df["Age"].mean()

In [26]:
mean_age

38.92149214921492

In [27]:
df["Age"].fillna(mean_age)

0       38.921492
1       41.000000
2       42.000000
3       39.000000
4       43.000000
          ...
9995    39.000000
9996    35.000000
9997    36.000000
9998    42.000000
9999    28.000000
Name: Age, Length: 10000, dtype: float64

In [29]:
# alternative way of doing it 
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [30]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Latest_Balance,Random Column
0,1,15634602,Hargrave,619,France,Female,38.921492,2,0.00,1,1,1,101348.88,1,500.00,Good day
1,2,15647311,Hill,608,Spain,Female,41.000000,1,83807.86,1,0,1,112542.58,0,84307.86,Good day
2,3,15619304,Onio,502,France,Female,42.000000,8,159660.80,3,1,0,113931.57,1,160160.80,Good day
3,4,15701354,Boni,699,France,Female,39.000000,1,0.00,2,0,0,93826.63,0,500.00,Good day
4,5,15737888,Mitchell,850,Spain,Female,43.000000,2,125510.82,1,1,1,79084.10,0,126010.82,Good day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39.000000,5,0.00,2,1,0,96270.64,0,500.00,Good day
9996,9997,15569892,Johnstone,516,France,Male,35.000000,10,57369.61,1,1,1,101699.77,0,57869.61,Good day
9997,9998,15584532,Liu,709,France,Female,36.000000,7,0.00,1,0,1,42085.58,1,500.00,Good day
9998,9999,15682355,Sabbatini,772,Germany,Male,42.000000,3,75075.31,2,1,0,92888.52,1,75575.31,Good day
9999,10000,15628319,Walker,792,France,Female,28.000000,4,130142.79,1,1,0,38190.78,0,130642.79,Good day

In [33]:
# drop all the null values in Age column
df["Age"] = df["Age"].dropna()

In [34]:
# to remove a column completely 
df.pop("RowNumber")

0           1
1           2
2           3
3           4
4           5
        ...
9995     9996
9996     9997
9997     9998
9998     9999
9999    10000
Name: RowNumber, Length: 10000, dtype: int64

In [35]:
df.head(5)

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Latest_Balance,Random Column
0,15634602,Hargrave,619,France,Female,38.921492,2,0.00,1,1,1,101348.88,1,500.00,Good day
1,15647311,Hill,608,Spain,Female,41.000000,1,83807.86,1,0,1,112542.58,0,84307.86,Good day
2,15619304,Onio,502,France,Female,42.000000,8,159660.80,3,1,0,113931.57,1,160160.80,Good day
3,15701354,Boni,699,France,Female,39.000000,1,0.00,2,0,0,93826.63,0,500.00,Good day
4,15737888,Mitchell,850,Spain,Female,43.000000,2,125510.82,1,1,1,79084.10,0,126010.82,Good day

In [36]:
# alternative way to drop a column 
df = df.drop("CustomerId", axis=1)

In [37]:
df

,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Latest_Balance,Random Column
0,Hargrave,619,France,Female,38.921492,2,0.00,1,1,1,101348.88,1,500.00,Good day
1,Hill,608,Spain,Female,41.000000,1,83807.86,1,0,1,112542.58,0,84307.86,Good day
2,Onio,502,France,Female,42.000000,8,159660.80,3,1,0,113931.57,1,160160.80,Good day
3,Boni,699,France,Female,39.000000,1,0.00,2,0,0,93826.63,0,500.00,Good day
4,Mitchell,850,Spain,Female,43.000000,2,125510.82,1,1,1,79084.10,0,126010.82,Good day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Obijiaku,771,France,Male,39.000000,5,0.00,2,1,0,96270.64,0,500.00,Good day
9996,Johnstone,516,France,Male,35.000000,10,57369.61,1,1,1,101699.77,0,57869.61,Good day
9997,Liu,709,France,Female,36.000000,7,0.00,1,0,1,42085.58,1,500.00,Good day
9998,Sabbatini,772,Germany,Male,42.000000,3,75075.31,2,1,0,92888.52,1,75575.31,Good day
9999,Walker,792,France,Female,28.000000,4,130142.79,1,1,0,38190.78,0,130642.79,Good day

In [38]:
# replace gender with 1 and 0
df["Gender"]=df["Gender"].replace({"Male": 1, "Female": 0})

In [39]:
df

,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Latest_Balance,Random Column
0,Hargrave,619,France,0,38.921492,2,0.00,1,1,1,101348.88,1,500.00,Good day
1,Hill,608,Spain,0,41.000000,1,83807.86,1,0,1,112542.58,0,84307.86,Good day
2,Onio,502,France,0,42.000000,8,159660.80,3,1,0,113931.57,1,160160.80,Good day
3,Boni,699,France,0,39.000000,1,0.00,2,0,0,93826.63,0,500.00,Good day
4,Mitchell,850,Spain,0,43.000000,2,125510.82,1,1,1,79084.10,0,126010.82,Good day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Obijiaku,771,France,1,39.000000,5,0.00,2,1,0,96270.64,0,500.00,Good day
9996,Johnstone,516,France,1,35.000000,10,57369.61,1,1,1,101699.77,0,57869.61,Good day
9997,Liu,709,France,0,36.000000,7,0.00,1,0,1,42085.58,1,500.00,Good day
9998,Sabbatini,772,Germany,1,42.000000,3,75075.31,2,1,0,92888.52,1,75575.31,Good day
9999,Walker,792,France,0,28.000000,4,130142.79,1,1,0,38190.78,0,130642.79,Good day

In [40]:
df["Balance"]

0            0.00
1        83807.86
2       159660.80
3            0.00
4       125510.82
          ...
9995         0.00
9996     57369.61
9997         0.00
9998     75075.31
9999    130142.79
Name: Balance, Length: 10000, dtype: float64

In [41]:
# find the square root
df["Balance"] = df["Balance"].apply(np.sqrt)

In [42]:
df["Balance"]

0         0.000000
1       289.495872
2       399.575775
3         0.000000
4       354.275063
           ...
9995      0.000000
9996    239.519540
9997      0.000000
9998    273.998741
9999    360.753087
Name: Balance, Length: 10000, dtype: float64

In [43]:
# create a column and apply the square root
df["Square Balance"] = df["Balance"].apply(np.sqrt)

In [44]:
df

,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Latest_Balance,Random Column,Square Balance
0,Hargrave,619,France,0,38.921492,2,0.000000,1,1,1,101348.88,1,500.00,Good day,0.000000
1,Hill,608,Spain,0,41.000000,1,289.495872,1,0,1,112542.58,0,84307.86,Good day,17.014578
2,Onio,502,France,0,42.000000,8,399.575775,3,1,0,113931.57,1,160160.80,Good day,19.989392
3,Boni,699,France,0,39.000000,1,0.000000,2,0,0,93826.63,0,500.00,Good day,0.000000
4,Mitchell,850,Spain,0,43.000000,2,354.275063,1,1,1,79084.10,0,126010.82,Good day,18.822196
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Obijiaku,771,France,1,39.000000,5,0.000000,2,1,0,96270.64,0,500.00,Good day,0.000000
9996,Johnstone,516,France,1,35.000000,10,239.519540,1,1,1,101699.77,0,57869.61,Good day,15.476419
9997,Liu,709,France,0,36.000000,7,0.000000,1,0,1,42085.58,1,500.00,Good day,0.000000
9998,Sabbatini,772,Germany,1,42.000000,3,273.998741,2,1,0,92888.52,1,75575.31,Good day,16.552907
9999,Walker,792,France,0,28.000000,4,360.753087,1,1,0,38190.78,0,130642.79,Good day,18.993501

In [45]:
df.dropna()

,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Latest_Balance,Random Column,Square Balance
0,Hargrave,619,France,0,38.921492,2,0.000000,1,1,1,101348.88,1,500.00,Good day,0.000000
1,Hill,608,Spain,0,41.000000,1,289.495872,1,0,1,112542.58,0,84307.86,Good day,17.014578
2,Onio,502,France,0,42.000000,8,399.575775,3,1,0,113931.57,1,160160.80,Good day,19.989392
3,Boni,699,France,0,39.000000,1,0.000000,2,0,0,93826.63,0,500.00,Good day,0.000000
4,Mitchell,850,Spain,0,43.000000,2,354.275063,1,1,1,79084.10,0,126010.82,Good day,18.822196
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Obijiaku,771,France,1,39.000000,5,0.000000,2,1,0,96270.64,0,500.00,Good day,0.000000
9996,Johnstone,516,France,1,35.000000,10,239.519540,1,1,1,101699.77,0,57869.61,Good day,15.476419
9997,Liu,709,France,0,36.000000,7,0.000000,1,0,1,42085.58,1,500.00,Good day,0.000000
9998,Sabbatini,772,Germany,1,42.000000,3,273.998741,2,1,0,92888.52,1,75575.31,Good day,16.552907
9999,Walker,792,France,0,28.000000,4,360.753087,1,1,0,38190.78,0,130642.79,Good day,18.993501

In [46]:
# Concat & merging

In [47]:
import pandas as pd

df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'], 
                    'B': ['B0', 'B1', 'B2', 'B3'], 
                    'C': ['C0', 'C1', 'C2', 'C3'], 
                    'D': ['D0', 'D1', 'D2', 'D3']}, 
                  index=[0,1,2,3])

In [48]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [49]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'], 
                    'B': ['B4', 'B5', 'B6', 'B7'], 
                    'C': ['C4', 'C5', 'C6', 'C7'], 
                    'D': ['D4', 'D5', 'D6', 'D7']}, 
                  index=[4,5,6,7])

In [50]:
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [51]:
result = pd.concat([df1,df2])

In [52]:
result

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

 loc vs iloc

In [53]:
s = pd.Series(list("abcdef"), index=[49, 48, 47, 0, 1, 2]) 
s

49    a
48    b
47    c
0     d
1     e
2     f
dtype: object

In [54]:
s.loc[0] # i.e locate the value of label of key 0

'd'

In [55]:
s.loc[49] # locate the value of label of key 49

'a'

In [56]:
s.loc[0:1]    # locate the value of label of key 0 to 1

0    d
1    e
dtype: object

In [61]:
s.loc[49:48]   # locate the value of label of key 49 to 48

49    a
48    b
dtype: object

In [62]:
s.iloc[0] # index location not label

'a'

In [64]:
s.iloc[0:5]  # index location not label

49    a
48    b
47    c
0     d
1     e
dtype: object

sort the series

In [67]:
s = s.sort_index() # this will rearrange the series

In [66]:
s

0     d
1     e
2     f
47    c
48    b
49    a
dtype: object

In [69]:
# now let apply index location 
s.iloc[0]

'd'

In [70]:
s.iloc[0:2]

0    d
1    e
dtype: object

In [71]:
# let see label
s.loc[0]

'd'

In [73]:
s.loc[0:2] # this is because it has been arranged

0    d
1    e
2    f
dtype: object

In [74]:
s.loc[0:49] # location dealas with label and it will start counting from 1 not 0

0     d
1     e
2     f
47    c
48    b
49    a
dtype: object

In [76]:
s.iloc[0:6] # this start from index of 0 to 5 hence the 6

0     d
1     e
2     f
47    c
48    b
49    a
dtype: object