In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Churn_Modelling.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,NaN,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39.0,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35.0,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36.0,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1,0,38190.78,0

In [4]:
# view the data 
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,NaN,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0

In [5]:
df.tail()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,9996,15606229,Obijiaku,771,France,Male,39.0,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35.0,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36.0,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1,0,38190.78,0

In [7]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,9999.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921492,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.488286,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              9999 non-null   float64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(3), int64(8), object(3)
memory usage: 1.1+ MB

In [9]:
#accessing columns
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [11]:
df["Age"] # single column

0        NaN
1       41.0
2       42.0
3       39.0
4       43.0
        ...
9995    39.0
9996    35.0
9997    36.0
9998    42.0
9999    28.0
Name: Age, Length: 10000, dtype: float64

In [12]:
df[["Gender","Age"]] # multiple columns

      Gender   Age
0     Female   NaN
1     Female  41.0
2     Female  42.0
3     Female  39.0
4     Female  43.0
...      ...   ...
9995    Male  39.0
9996    Male  35.0
9997  Female  36.0
9998    Male  42.0
9999  Female  28.0

[10000 rows x 2 columns]

In [13]:
# accessing rows
df.iloc[0] # single row by index

RowNumber                  1
CustomerId          15634602
Surname             Hargrave
CreditScore              619
Geography             France
Gender                Female
Age                      NaN
Tenure                     2
Balance                  0.0
NumOfProducts              1
HasCrCard                  1
IsActiveMember             1
EstimatedSalary    101348.88
Exited                     1
Name: 0, dtype: object

In [14]:
df.iloc[0:5] # first 5 rows

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,NaN,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0

In [15]:
df.iloc[0, 2] # first rows and 3rd column

'Hargrave'

In [16]:
df.iloc[0:2, 0:2]   # First 2 rows and first 2 columns

   RowNumber  CustomerId
0          1    15634602
1          2    15647311

In [17]:
# accessing rows by label
df.loc[0] # single row by label

RowNumber                  1
CustomerId          15634602
Surname             Hargrave
CreditScore              619
Geography             France
Gender                Female
Age                      NaN
Tenure                     2
Balance                  0.0
NumOfProducts              1
HasCrCard                  1
IsActiveMember             1
EstimatedSalary    101348.88
Exited                     1
Name: 0, dtype: object

In [18]:
df.loc[0, "Surname"] # first row and surname column as label

'Hargrave'

In [21]:
df.loc[1]  # Returns the row with index label 1:

RowNumber                  2
CustomerId          15647311
Surname                 Hill
CreditScore              608
Geography              Spain
Gender                Female
Age                     41.0
Tenure                     1
Balance             83807.86
NumOfProducts              1
HasCrCard                  0
IsActiveMember             1
EstimatedSalary    112542.58
Exited                     0
Name: 1, dtype: object

In [23]:
# filtering data
df[df['Age'] > 30]  # filter rows where age is greater than 30

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44.0,8,113755.78,2,1,0,149756.71,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,9993,15657105,Chukwualuka,726,Spain,Male,36.0,2,0.00,1,1,0,195192.40,0
9995,9996,15606229,Obijiaku,771,France,Male,39.0,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35.0,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36.0,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1,0,92888.52,1

In [25]:
# Alternative way
df.query("Age > 30")

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44.0,8,113755.78,2,1,0,149756.71,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,9993,15657105,Chukwualuka,726,Spain,Male,36.0,2,0.00,1,1,0,195192.40,0
9995,9996,15606229,Obijiaku,771,France,Male,39.0,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35.0,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36.0,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1,0,92888.52,1

In [26]:
# Using loc for more clarity
df.loc[df['Age'] > 30]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44.0,8,113755.78,2,1,0,149756.71,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,9993,15657105,Chukwualuka,726,Spain,Male,36.0,2,0.00,1,1,0,195192.40,0
9995,9996,15606229,Obijiaku,771,France,Male,39.0,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35.0,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36.0,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1,0,92888.52,1

In [27]:
# Multiple conditions example
df.loc[(df['Age'] > 30) & (df['Age'] < 50)]

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44.0,8,113755.78,2,1,0,149756.71,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,9993,15657105,Chukwualuka,726,Spain,Male,36.0,2,0.00,1,1,0,195192.40,0
9995,9996,15606229,Obijiaku,771,France,Male,39.0,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35.0,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36.0,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1,0,92888.52,1

In [36]:
# With specific columns
df.loc[df['Age'] > 30, ['Surname', 'Age', 'Balance']]

          Surname   Age    Balance
1            Hill  41.0   83807.86
2            Onio  42.0  159660.80
3            Boni  39.0       0.00
4        Mitchell  43.0  125510.82
5             Chu  44.0  113755.78
...           ...   ...        ...
9992  Chukwualuka  36.0       0.00
9995     Obijiaku  39.0       0.00
9996    Johnstone  35.0   57369.61
9997          Liu  36.0       0.00
9998    Sabbatini  42.0   75075.31

[8031 rows x 3 columns]

In [28]:
# Transpose column
df.T

,0,1,2,3,4,5,6,7,8,9,...,9990,9991,9992,9993,9994,9995,9996,9997,9998,9999
RowNumber,1,2,3,4,5,6,7,8,9,10,...,9991,9992,9993,9994,9995,9996,9997,9998,9999,10000
CustomerId,15634602,15647311,15619304,15701354,15737888,15574012,15592531,15656148,15792365,15592389,...,15798964,15769959,15657105,15569266,15719294,15606229,15569892,15584532,15682355,15628319
Surname,Hargrave,Hill,Onio,Boni,Mitchell,Chu,Bartlett,Obinna,He,H?,...,Nkemakonam,Ajuluchukwu,Chukwualuka,Rahman,Wood,Obijiaku,Johnstone,Liu,Sabbatini,Walker
CreditScore,619,608,502,699,850,645,822,376,501,684,...,714,597,726,644,800,771,516,709,772,792
Geography,France,Spain,France,France,Spain,Spain,France,Germany,France,France,...,Germany,France,Spain,France,France,France,France,France,Germany,France
Gender,Female,Female,Female,Female,Female,Male,Male,Female,Male,Male,...,Male,Female,Male,Male,Female,Male,Male,Female,Male,Female
Age,NaN,41.0,42.0,39.0,43.0,44.0,50.0,29.0,44.0,27.0,...,33.0,53.0,36.0,28.0,29.0,39.0,35.0,36.0,42.0,28.0
Tenure,2,1,8,1,2,8,7,4,4,2,...,3,4,2,7,2,5,10,7,3,4
Balance,0.0,83807.86,159660.8,0.0,125510.82,113755.78,0.0,115046.74,142051.07,134603.88,...,35016.6,88381.21,0.0,155060.41,0.0,0.0,57369.61,0.0,75075.31,130142.79
NumOfProducts,1,1,3,2,1,2,2,4,2,1,...,1,1,1,1,2,2,1,1,2,1
HasCrCard,1,0,1,0,1,1,1,1,0,1,...,1,1,1,1,0,1,1,0,1,1
IsActiveMember,1,1,0,0,1,0,1,0,1,1,...,0,0,0,0,0,0,1,1,0,0
EstimatedSalary,101348.88,112542.58,113931.57,93826.63,79084.1,149756.71,10062.8,119346.88,74940.5,71725.73,...,53667.08,69384.71,195192.4,29179.52,167773.55,96270.64,101699.77,42085.58,92888.52,38190.78
Exited,1,0,1,0,0,1,0,1,0,0,...,0,1,0,0,0,0,0,1,1,0

In [29]:
# sort your dataframe base on age
df.sort_values("Age")

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9932,9933,15813451,Fleetwood-Smith,677,Spain,Male,18.0,8,134796.87,2,1,1,114858.90,0
3330,3331,15657439,Chao,738,France,Male,18.0,4,0.00,2,1,1,47799.15,0
8522,8523,15619892,Page,644,Spain,Male,18.0,8,0.00,2,1,0,59172.42,0
9520,9521,15673180,Onyekaozulu,727,Germany,Female,18.0,2,93816.70,2,1,0,126172.11,0
4556,4557,15796231,Nwankwo,681,France,Female,18.0,1,98894.39,1,1,1,9596.40,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3033,3034,15578006,Yao,787,France,Female,85.0,10,0.00,2,1,1,116537.96,0
2458,2459,15813303,Rearick,513,Spain,Male,88.0,10,0.00,2,1,1,52952.24,0
6759,6760,15660878,T'ien,705,France,Male,92.0,1,126076.24,2,1,1,34436.83,0
6443,6444,15764927,Rogova,753,France,Male,92.0,3,121513.31,1,0,1,195563.99,0
0,1,15634602,Hargrave,619,France,Female,NaN,2,0.00,1,1,1,101348.88,1

In [ ]:
# create new column in a dataframe and assigned value 
df["New Balance me"]= df["Balance"] *2
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance me
0,1,15634602,Hargrave,619,France,Female,NaN,2,0.00,1,1,1,101348.88,1,0.00
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0,167615.72
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1,319321.60
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0,0.00
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0,251021.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39.0,5,0.00,2,1,0,96270.64,0,0.00
9996,9997,15569892,Johnstone,516,France,Male,35.0,10,57369.61,1,1,1,101699.77,0,114739.22
9997,9998,15584532,Liu,709,France,Female,36.0,7,0.00,1,0,1,42085.58,1,0.00
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1,0,92888.52,1,150150.62
9999,10000,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1,0,38190.78,0,260285.58

In [34]:
# assigned new column with values
df["Random column"] = "Good day"
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance me,Random column
0,1,15634602,Hargrave,619,France,Female,NaN,2,0.00,1,1,1,101348.88,1,0.00,Good day
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0,1,112542.58,0,167615.72,Good day
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1,0,113931.57,1,319321.60,Good day
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0,0,93826.63,0,0.00,Good day
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,1,1,79084.10,0,251021.64,Good day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39.0,5,0.00,2,1,0,96270.64,0,0.00,Good day
9996,9997,15569892,Johnstone,516,France,Male,35.0,10,57369.61,1,1,1,101699.77,0,114739.22,Good day
9997,9998,15584532,Liu,709,France,Female,36.0,7,0.00,1,0,1,42085.58,1,0.00,Good day
9998,9999,15682355,Sabbatini,772,Germany,Male,42.0,3,75075.31,2,1,0,92888.52,1,150150.62,Good day
9999,10000,15628319,Walker,792,France,Female,28.0,4,130142.79,1,1,0,38190.78,0,260285.58,Good day

In [35]:
# creating new df but only if the condition is met
new_df_age_gretarer_50 = df[df["Age"]> 50]

In [38]:
new_df_age_gretarer_50.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance me,Random column
16,17,15737452,Romeo,653,Germany,Male,58.0,1,132602.88,1,1,0,5097.67,1,265205.76,Good day
41,42,15738148,Clarke,465,France,Female,51.0,8,122522.32,1,0,0,181297.65,1,245044.64,Good day
42,43,15687946,Osborne,556,France,Female,61.0,2,117419.35,1,1,1,94153.83,0,234838.70,Good day
44,45,15684171,Bianchi,660,Spain,Female,61.0,5,155931.11,1,1,1,158338.39,0,311862.22,Good day
58,59,15623944,T'ien,511,Spain,Female,66.0,4,0.00,1,1,0,1643.11,1,0.00,Good day

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              9999 non-null   float64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
 14  New Balance me   10000 non-null  float64
 15  Random column    10000 non-null  object
dtypes: float64(4), int64(8), object(4)
memory usage: 1.2+ MB

In [40]:
df["Age"].isnull().sum()

np.int64(1)

In [41]:
mean_age = df["Age"].mean()
mean_age

np.float64(38.92149214921492)

In [48]:
# fill the null value with the mean age 
df["Age"].fillna(df["Age"].mean(), inplace = True)
df

#or 
#df["Age"].fillna(mean_age, inplace=True)
#df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance me,Random column
0,1,15634602,Hargrave,619,France,Female,38.921492,2,0.00,1,1,1,101348.88,1,0.00,Good day
1,2,15647311,Hill,608,Spain,Female,38.921492,1,83807.86,1,0,1,112542.58,0,167615.72,Good day
2,3,15619304,Onio,502,France,Female,38.921492,8,159660.80,3,1,0,113931.57,1,319321.60,Good day
3,4,15701354,Boni,699,France,Female,38.921492,1,0.00,2,0,0,93826.63,0,0.00,Good day
4,5,15737888,Mitchell,850,Spain,Female,38.921492,2,125510.82,1,1,1,79084.10,0,251021.64,Good day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,38.921492,5,0.00,2,1,0,96270.64,0,0.00,Good day
9996,9997,15569892,Johnstone,516,France,Male,38.921492,10,57369.61,1,1,1,101699.77,0,114739.22,Good day
9997,9998,15584532,Liu,709,France,Female,38.921492,7,0.00,1,0,1,42085.58,1,0.00,Good day
9998,9999,15682355,Sabbatini,772,Germany,Male,38.921492,3,75075.31,2,1,0,92888.52,1,150150.62,Good day
9999,10000,15628319,Walker,792,France,Female,38.921492,4,130142.79,1,1,0,38190.78,0,260285.58,Good day

In [49]:
df["Age"].isnull().sum()

np.int64(0)

In [51]:
# drop all the null values in the age column
df["Age"].dropna(inplace=True)
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance me,Random column
0,1,15634602,Hargrave,619,France,Female,38.921492,2,0.00,1,1,1,101348.88,1,0.00,Good day
1,2,15647311,Hill,608,Spain,Female,38.921492,1,83807.86,1,0,1,112542.58,0,167615.72,Good day
2,3,15619304,Onio,502,France,Female,38.921492,8,159660.80,3,1,0,113931.57,1,319321.60,Good day
3,4,15701354,Boni,699,France,Female,38.921492,1,0.00,2,0,0,93826.63,0,0.00,Good day
4,5,15737888,Mitchell,850,Spain,Female,38.921492,2,125510.82,1,1,1,79084.10,0,251021.64,Good day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,38.921492,5,0.00,2,1,0,96270.64,0,0.00,Good day
9996,9997,15569892,Johnstone,516,France,Male,38.921492,10,57369.61,1,1,1,101699.77,0,114739.22,Good day
9997,9998,15584532,Liu,709,France,Female,38.921492,7,0.00,1,0,1,42085.58,1,0.00,Good day
9998,9999,15682355,Sabbatini,772,Germany,Male,38.921492,3,75075.31,2,1,0,92888.52,1,150150.62,Good day
9999,10000,15628319,Walker,792,France,Female,38.921492,4,130142.79,1,1,0,38190.78,0,260285.58,Good day

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  float64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
 14  New Balance me   10000 non-null  float64
 15  Random column    10000 non-null  object
dtypes: float64(4), int64(8), object(4)
memory usage: 1.2+ MB

In [55]:
# delete one of the column
df.pop("RowNumber")

0           1
1           2
2           3
3           4
4           5
        ...
9995     9996
9996     9997
9997     9998
9998     9999
9999    10000
Name: RowNumber, Length: 10000, dtype: int64

In [56]:
df.head()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance me,Random column
0,15634602,Hargrave,619,France,Female,38.921492,2,0.00,1,1,1,101348.88,1,0.00,Good day
1,15647311,Hill,608,Spain,Female,38.921492,1,83807.86,1,0,1,112542.58,0,167615.72,Good day
2,15619304,Onio,502,France,Female,38.921492,8,159660.80,3,1,0,113931.57,1,319321.60,Good day
3,15701354,Boni,699,France,Female,38.921492,1,0.00,2,0,0,93826.63,0,0.00,Good day
4,15737888,Mitchell,850,Spain,Female,38.921492,2,125510.82,1,1,1,79084.10,0,251021.64,Good day

In [64]:
# check if column in dataframe
print(df.columns.tolist())

['Surname', 'CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Exited', 'New Balance me', 'Random column']

In [65]:
df.head()

,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance me,Random column
0,Hargrave,619,France,Female,38.921492,2,0.00,1,1,1,101348.88,1,0.00,Good day
1,Hill,608,Spain,Female,38.921492,1,83807.86,1,0,1,112542.58,0,167615.72,Good day
2,Onio,502,France,Female,38.921492,8,159660.80,3,1,0,113931.57,1,319321.60,Good day
3,Boni,699,France,Female,38.921492,1,0.00,2,0,0,93826.63,0,0.00,Good day
4,Mitchell,850,Spain,Female,38.921492,2,125510.82,1,1,1,79084.10,0,251021.64,Good day

In [67]:
if "Gender" in df.columns:
    df= df.drop("Gender", axis=1)

In [70]:
df.head()

,Surname,CreditScore,Geography,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance me,Random column
0,Hargrave,619,France,38.921492,2,0.00,1,1,1,101348.88,1,0.00,Good day
1,Hill,608,Spain,38.921492,1,83807.86,1,0,1,112542.58,0,167615.72,Good day
2,Onio,502,France,38.921492,8,159660.80,3,1,0,113931.57,1,319321.60,Good day
3,Boni,699,France,38.921492,1,0.00,2,0,0,93826.63,0,0.00,Good day
4,Mitchell,850,Spain,38.921492,2,125510.82,1,1,1,79084.10,0,251021.64,Good day

In [71]:
df["Balance"]

0            0.00
1        83807.86
2       159660.80
3            0.00
4       125510.82
          ...
9995         0.00
9996     57369.61
9997         0.00
9998     75075.31
9999    130142.79
Name: Balance, Length: 10000, dtype: float64

In [72]:
df["Balance"].apply(np.sqrt)

0         0.000000
1       289.495872
2       399.575775
3         0.000000
4       354.275063
           ...
9995      0.000000
9996    239.519540
9997      0.000000
9998    273.998741
9999    360.753087
Name: Balance, Length: 10000, dtype: float64

In [73]:
df["sqrt column"] = df["Balance"].apply(np.sqrt)

In [75]:
df.head()

,Surname,CreditScore,Geography,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,New Balance me,Random column,sqrt column
0,Hargrave,619,France,38.921492,2,0.00,1,1,1,101348.88,1,0.00,Good day,0.000000
1,Hill,608,Spain,38.921492,1,83807.86,1,0,1,112542.58,0,167615.72,Good day,289.495872
2,Onio,502,France,38.921492,8,159660.80,3,1,0,113931.57,1,319321.60,Good day,399.575775
3,Boni,699,France,38.921492,1,0.00,2,0,0,93826.63,0,0.00,Good day,0.000000
4,Mitchell,850,Spain,38.921492,2,125510.82,1,1,1,79084.10,0,251021.64,Good day,354.275063

In [76]:
df.isnull().sum()

Surname            0
CreditScore        0
Geography          0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
New Balance me     0
Random column      0
sqrt column        0
dtype: int64

In [78]:
dff = pd.DataFrame({
    'A': [1, None, 3],
    'B': [4, 5, None],
    'C': [7, 8, 9]
})

In [79]:
dff

     A    B  C
0  1.0  4.0  7
1  NaN  5.0  8
2  3.0  NaN  9

In [81]:
dff.isnull().sum()

A    1
B    1
C    0
dtype: int64

In [82]:
df.dropna(subset=["A","B"],inplace=True)

In [83]:
dff

     A    B  C
0  1.0  4.0  7
1  NaN  5.0  8
2  3.0  NaN  9

In [84]:
dff.dropna()
dff

     A    B  C
0  1.0  4.0  7
1  NaN  5.0  8
2  3.0  NaN  9

In [85]:
dff.fillna(df["A"].mean(), inplace=True)

In [86]:
dff

     A    B  C
0  1.0  4.0  7
1  1.0  5.0  8
2  3.0  1.0  9

In [88]:
dff

     A    B  C
0  1.0  4.0  7
1  1.0  5.0  8
2  3.0  1.0  9